### ISSUE TITLE
Sistemare i redirect

### ISSUE THREAD

**Issue by ScrappyCocco** [frncscdf/Tecnologie-Web#14]
- ~~Cambiare colore all'immagine SVG (controllare se i colori vanno bene -> controllo contrasto)~~

- ~~Mettere l'ID al commento quando si fa il redirect dopo un voto (l'id c'è ma il redirect non va)~~

- ~~Sistemare il CSS del nuovo form usato per votare~~

- ~~Il sistema di cambio voto non funziona (tolgo il voto o metto il voto opposto)~~

- ~~Aggiungere l'eliminazione del proprio commento~~

**Comment by frncscdf** [comment]
- Login redirect sulla pagina su cui si stava navigando
- Cancellazione del commento da testare

**Comment by ScrappyCocco** [comment]
Issue aggiornata segnando le cose principali fatte
