### ISSUE TITLE
Sistemare testo nei commenti

### ISSUE THREAD

**Issue by frncscdf** [frncscdf/Tecnologie-Web#21]
[
<img width="1289" alt="schermata 2018-12-19 alle 18 18 38" src="https://user-images.githubusercontent.com/29098430/50236382-8b74d180-03ba-11e9-9159-8a57729fdb76.png">
](url)

**Comment by ScrappyCocco** [comment]
Fixed in [https://github.com/frncscdf/Tecnologie-Web/commit/b7b9addc5c36a34c15e08cc66f01a8d63e5fe824](https://github.com/frncscdf/Tecnologie-Web/commit/b7b9addc5c36a34c15e08cc66f01a8d63e5fe824)
