### ISSUE TITLE
Aggiustamenti da fare a profile

### ISSUE THREAD

**Issue by ScrappyCocco** [frncscdf/Tecnologie-Web#25]
- Decidere se lasciare il "Bentornato, <nick>", considerare l'idea di mettere la mail che non viene cambiata
- Rinominare un minimo le label delle password come il placeholder in maniera che non dicano entrambe "Password"
- Considerare l'aggiunta della casella di conferma della nuova password ed eventuali controlli di uguaglianza in js
- Aggiungere la richiesta di conferma prima di eliminare l'account

**Comment by frncscdf** [comment]
- [ ] Decidere se lasciare il "Bentornato, ", considerare l'idea di mettere la mail che non viene cambiata

- [ ] Rinominare un minimo le label delle password come il placeholder in maniera che non dicano entrambe "Password"
Fatte solo quelle in profile.php

- Considerare l'aggiunta della casella di conferma della nuova password ed eventuali controlli di uguaglianza in js
Si, metti nella issue per la gestione degli errori client side in js 

- [ ] Aggiungere la richiesta di conferma prima di eliminare l'account
Fatta, ma va messa ancora o spostati i tasti in alto

**Comment by ScrappyCocco** [comment]
Abbiamo discusso con Barzy e i bottoni non stavano bene nella stessa pagina di profile in nessun punto, abbiamo optato per fare una pagina di conferma a parte.
Piu' semplice da gestire e anche a livello di accessibilita', ci conviene.
