### ISSUE TITLE
Requisito opzionale: Creare una pagina profile per vedere il profilo di un altro utente

### ISSUE THREAD

**Issue by ScrappyCocco** [frncscdf/Tecnologie-Web#33]
Se abbiamo tempo, creiamo una pagina per visualizzare i dati di un altro utente, come il nome, il cognome, se ha scritto articoli (e quali) e se ha scritto commenti (e quali)

**Comment by frncscdf** [comment]
Sfruttare bio card

**Comment by frncscdf** [comment]
Non si fa
