### ISSUE TITLE
Aggiustare il Css (togliere !important)

### ISSUE THREAD

**Issue by ScrappyCocco** [frncscdf/Tecnologie-Web#46]
Per fare la scritta nera nella navbar ho momentaneamente messo important, sarebbe meglio toglierlo ma cosi' l'elemento eredita menu > li, che non voglio blu visto che non e' un link.
Prova a vedere se si puo' sistemare.

https://github.com/frncscdf/Tecnologie-Web/blob/8fb6073fe770493b75de4c9f6954fdad62c9ca7b/style.css#L142

**Comment by Giacomobarzon97** [comment]
dove lo usi current-menu-entry?
