### ISSUE TITLE
Contenuti del sito

### ISSUE THREAD

**Issue by frncscdf** [frncscdf/Tecnologie-Web#51]
Sarebbe buona cosa iniziare a scrivere i contenuti veri, in questo modo possiamo avere un'istanza reale del sito.
Io direi:
- 6 card (quindi macroargomenti)
- Per ciascuno dei 6 creare un paio di sottoargomenti (qualche card ne avrà 4, altre 3, altre solo 1, ecc.)
- Per ciascun sottoargomento un paio di articoli (qualcuno ne avrà 2/3, altri solo 1 e qualcuno vuoto).

Gli argomenti delle 6 card possono essere:
- Algoritmi
- Sistemi Operativi
- Architettura degli Elaboratori
- Automi
- Programmazione nel linguaggio X
- Reti

**Comment by giacomogreggio** [comment]
Only english

**Comment by giacomogreggio** [comment]
Algoritmi: sottoargomenti: Programmazione dinamica(articoli: Compute Programming, Fibonacci, Dijkstra), Alberi binari di ricerca(articoli: Red-Black trees)

**Comment by giacomogreggio** [comment]
Operating system: sottoargomenti: Kernel(articoli: Process computing, Interrupts, Memory Management)

**Comment by giacomogreggio** [comment]
Computer organization and architecture: sottoargomenti: Von Neaumann architecture(no articoli)

**Comment by giacomogreggio** [comment]
Automata theory and functionals languages: sottoargomenti: Variant definitions of automata(no articoli), Class of automata(articoli: DPDA,PDA,NFA,Turing Machine)

**Comment by giacomogreggio** [comment]
Programming in Java: sottoargomenti: Trails Covering the Basics(articoli: Getting started), Creating Graphical User Interfaces(articoli: no), Specialized Trails and Lessons(articoli: Custom Networking, Generics,)

**Comment by giacomogreggio** [comment]
Computer network(no sottoargomenti(aggiungere in caso))

**Comment by giacomogreggio** [comment]
Modificare tutti gli articoli in modo che gli h3 diventino h2 e gli h4 diventino h3. Abilitare h2 sulla scrittura articolo.

**Comment by giacomogreggio** [comment]
Reinserire tutti i contenuti. Le descrizioni dei topic (NO SUBTOPIC quelle rimangono lunghe) vanno accorciate quando sono mostrate in anteprima su create_argument e estese solo una volta aperta la pagina dove crei subtopic
