### ISSUE TITLE
Sistemare h nella pagina articolo

### ISSUE THREAD

**Issue by Giacomobarzon97** [frncscdf/Tecnologie-Web#58]
partono da h2 e dovrebbero partire da h1

**Comment by ScrappyCocco** [comment]
Questo non vale solo per quella pagina, c'è di sicuro anche tipo in article links, bisogna controllarle un po' tutte

**Comment by ScrappyCocco** [comment]
@Giacomobarzon97 come lo sistemo? Perchè anche tu hai messo `<h1>` nel titolo della searchbar, ci metto `<h2>` lì? 
Quindi in article potremmo fare: titolo pagina in `<h1>` e il resto in `<h2>`?
Perchè pure il footer ha `<h1>`
