### ISSUE TITLE
Sistemare un po la sezione commenti

### ISSUE THREAD

**Issue by Giacomobarzon97** [frncscdf/Tecnologie-Web#60]

**Comment by ScrappyCocco** [comment]
Sistemare insieme al formato del commento anche la issue [https://github.com/frncscdf/Tecnologie-Web/issues/67](https://github.com/frncscdf/Tecnologie-Web/issues/67)

**Comment by ScrappyCocco** [comment]
(Basta scoprire come si è rotta l'ancora e abbiamo finito)

**Comment by ScrappyCocco** [comment]
Ancora sistemata, grazie barzy
