### ISSUE TITLE
Link in write article

### ISSUE THREAD

**Issue by frncscdf** [frncscdf/Tecnologie-Web#61]
- Argomento
- Sottoargomento
- Stai modificando l'articolo
Quello che viene riportato di fianco a queste voci sarebbe meglio scriverlo come link, quindi poter cliccare sull'informazione oltre che visualizzarla.
Oppure trovare un modo più "bello" per scrivere queste informazioni lavorando con un pò di CSS.

**Comment by Giacomobarzon97** [comment]
non e' gia' così ?

**Comment by Giacomobarzon97** [comment]
cioe' intendo i link dovrebbero gia' esserci (almeno per la parte front end). Sul modo più bello per esporli non ho idea di come poterlo fare. Se hai idee dimmi pure

**Comment by ScrappyCocco** [comment]
Link messi
