### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by frncscdf** [frncscdf/Tecnologie-Web#62]
- Cursor pointer sulle immagine per collassare/scollassare
- Poter chiudere anche le sezioni "attive", cioé quella selezionata dal breadcrumb

**Comment by ScrappyCocco** [comment]
@Giacomobarzon97 il fatto che non si possano chiudere quelle del breadcrumb credo sia colpa mia che probabilmente ho implementato male la cosa, prova a dare un'occhiata e dimmi se si può sistemare
