### ISSUE TITLE
Box messaggi di successo

### ISSUE THREAD

**Issue by frncscdf** [frncscdf/Tecnologie-Web#70]
Come per i messaggi di errore, utilizzare quello di colore verde per i messaggi di successo

**Comment by ScrappyCocco** [comment]
Messi in profile e registrazione, dove altro vanno?

- Gestire gli errori di upload immagine

**Comment by frncscdf** [comment]
Ban utente e aggiunta admin. C'è da modificare un attimo il messaggio di errore di questi con la classe di gestione errori.

**Comment by frncscdf** [comment]
nome immagine in fase di upload
