### ISSUE TITLE
Gestione errori eliminazione account

### ISSUE THREAD

**Issue by ScrappyCocco** [frncscdf/Tecnologie-Web#77]

**Comment by ScrappyCocco** [comment]
Redirect del logout

**Comment by frncscdf** [comment]
Pagina registrazione, cambiare tasto con "Registrati" invece di "submit"

**Comment by frncscdf** [comment]
Quando si accede ad adminTools senza permessi o login, scrivere opportuno messaggio (come manageArguments) e non riportare alla home

**Comment by frncscdf** [comment]
In Strumenti modificare il testo da "Crea nuovo argomento" a "Gestisci argomenti" visto che si possono anche cancellare
